name: Mirror to Bitbucket

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mirror to Bitbucket
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          git remote add bitbucket https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@bitbucket.org/comp3888_m12_02/comp3888_m12_02.git
          git push bitbucket --all --no-prune
          git push bitbucket --tags
